import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Modal from '../components/Modal'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Bug Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/*Header */}
      <Header />
  
      {/*Bug Feed*/}
      <Feed />

      {/* Modal */}
      <Modal /> 


      
    </div>
  )
}
