import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Header from '../components/Header'
import SideNav from '../components/SideNav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bug Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header */}
      <Header />
      {/*Side Nav */}
      

      {/*Bug Feed*/}
      <Feed />

      {/*Side Bar*/}

      
    </div>
  )
}
